### ISSUE TITLE
Messages reordered with Emacs 25 and shr

### ISSUE THREAD

**Issue by jech** [wanderlust/semi#11]
I'm using a fairly current Emacs 25 and using shr for displaying HTML mails.  When pressing `H' in the summary buffer on an HTML mail, the mail gets reordered — the body appears before the headers.

I haven't tried to debug it yet; the most obvious candidate is the change to the behaviour of `save-excursion`, which no longer preserves the mark.

**Comment by egh** [comment]
I guess this was a controversial change, but one not expected to break code.

Apparently the workaround is to use `save-mark-and-excursion`. I guess we need to check `(fboundp #'save-mark-and-excursion)` and use that function.

**Comment by egh** [comment]
On the other hand, I see no reference to `set-mark` and only one to `push-mark` in the WL codebase, so I'm not sure if that is the issue.

**Comment by egh** [comment]
https://github.com/wanderlust/flim/blob/488a4d70fb4ae57bdd30dc75c2d75579894e28a2/mel-u.el#L75

I think this should be fixed even if it is not the issue. The docs for `set-mark` say it should not be used for this purpose.

**Comment by ikazuhiro** [comment]
Please overwrite `mime-shr-preview-text/html` with below and test.

``` lisp
(defun mime-shr-preview-text/html (entity situation)
  (let ((dom (with-temp-buffer
           (mime-insert-text-content entity)
           (libxml-parse-html-region (point-min) (point-max))))
    (shr-content-function 'mime-shr-cid-retrieve)
    (shr-blocked-images (or mime-shr-blocked-images
                shr-blocked-images)))
    (setq mime-shr-root-entity (mime-find-root-entity entity))
    (save-restriction
      (narrow-to-region (point-max) (point-max))
      (shr-insert-document dom)))
  ;; Workaround to delete garbage overlay.
  (let ((overlays (overlays-in (point-min) (point-max))))
    (while overlays
      (when (eq (overlay-start (car overlays))
        (overlay-end (car overlays)))
    (delete-overlay (car overlays)))
      (setq overlays (cdr overlays)))))
```

**Comment by jech** [comment]
> Please overwrite mime-shr-preview-text/html with below and test.

It seems to fix the issue, or at least I'm unable to reproduce it.

Could you please explain what it does?  I find the code in SEMI completely 
incomprehensible.

-- Juliusz

**Comment by ikazuhiro** [comment]
I don't know the exact reason.  But the result indicates `shr-insert-document` may insert document before current point.

**Comment by ikazuhiro** [comment]
I've committed the change in https://github.com/wanderlust/semi/issues/11#issuecomment-104867655.
