### ISSUE TITLE
PGP defaults are broken

### ISSUE THREAD

**Issue by jech** [wanderlust/semi#2]
Even when pgg-default-scheme is set to gpg (the default), we try to use PGP5 in order to decode RSA-encrypted mail.  The workaround is to set

```
  (setq pgg-scheme 'gpg)
```

I don't fully understand the code, but I believe the guilty party is the stuff around line 90 in pgg.el.

--jch

**Comment by ikazuhiro** [comment]
Because SEMI-EPG doesn't use PGG anymore, I'll close this issue.
