### ISSUE TITLE
SEMI ignores `:` in url in text/plain part

### ISSUE THREAD

**Issue by catap** [wanderlust/semi#28]
Here an example of email where I've changed the real id to `XXX` and `123`:
```
[1  <multipart/alternative (7bit)>]
[1.1  <text/plain; UTF-8 (7bit)>]
UniFi Network is ready to update to 8.2.93

Install now: https://unifi.ui.com/consoles/XXX:123/applications

If you need additional help, please visit https://account.ui.com/mysupport
Regards,
The Ubiquiti team
[1.2  <multipart/related (7bit)>]
[1.2.1  <text/html; UTF-8 (quoted-printable)>]
[1.2.2 network.png <image/png (base64)>]
[1.2.3 b7054ed25ddf6464e6183f1122634e34.png <image/png (base64)>]
```

SEMI uses part up to `:` in the url, so, `browse-url-at-point` doesn't work because part `:123/applications` is missed from the url.

**Comment by ikazuhiro** [comment]
Please try follwoing code.

```elisp
(setq mime-browse-url-regexp browse-url-button-regexp)
```

**Comment by catap** [comment]
Yes, it help

**Comment by robohack** [comment]
I note that `browse-url-button-regexp` is only in Emacs 27.1 and newer....

**Comment by catap** [comment]
... which was released almost 4 years ago ...

**Comment by ikazuhiro** [comment]
I've committed the fix.  I avoided doing copy and paste regexp from browse-url.el due to license incompatibility (GPLv2 VS GPLv3).

**Comment by catap** [comment]
@ikazuhiro seems that it ignores `;` as well. I jsut got an email with links which contains `&amp;` and it is ignored:

![image](https://github.com/user-attachments/assets/aa14a43f-2355-4b74-91e8-71aa358ba38a)

**Comment by ikazuhiro** [comment]
Your example looks like a simple misusing of character entity reference, which should be used in html text, not plain text.  But, it seems grammatically valid.  If you use recent Emacs which has `browse-url-button-regexp` variable, the problem should be automativally fixed.  I'll adjust own regexp for Emacs 26 and earlier.

**Comment by catap** [comment]
Wired things: I use emacs 29.4 to take this screenshot.

**Comment by ikazuhiro** [comment]
Please confirm `mime-browse-url-regexp` and `browse-url-button-regexp` values.  If they are differnt each other, please set `mime-browse-url-regexp` explicitly.
```elisp
(setq mime-browse-url-regexp browse-url-button-regexp)
```

I confirmed `browse-url-button-regexp` worked correctly

```elisp
(let ((string
       "http://localhost/index.html?aaa=AAA&amp;bbb=BBB&amp;ccc=CCC"))
  (when (string-match browse-url-button-regexp string)
    (match-string 0 string)))
-> "http://localhost/index.html?aaa=AAA&amp;bbb=BBB&amp;ccc=CCC"
```

**Comment by catap** [comment]
Indeed `mime-browse-url-regexp` and `browse-url-button-regexp` is different. And after:
```
(setq mime-browse-url-regexp browse-url-button-regexp)
```

It works as expected.

I had checked it inside restarted emacs and only run `wl` inside it before test it.
