### ISSUE TITLE
Attachments in multipart/alternative are impossible to extract

### ISSUE THREAD

**Issue by jech** [wanderlust/semi#3]
Some people send me mails that contain a multipart/alternative with an attachment in the HTML part.  Although my wanderlust is configured to display the HTML part by default, such mails display the plain text part, and the attachment is impossible to extract.

Arguably, this is a bug in the sending mailer, but it would be nice to be able to extract an attachment without running another mail client.

Here's an example of such a mail:

```
--<<alternative>>-{
--[[text/plain]]
Text 1
--<<mixed>>-{
--[[text/html]]
<b>Text 2</b>
--[[application/octet-stream
Content-Disposition: attachment; filename="test"][7bit]]
Attachment
--[[text/plain]]
--}-<<mixed>>
--}-<<alternative>>
```

--jch

**Comment by ikazuhiro** [comment]
The problem had been fixed in default setting.  At present, Multipart is preferred to text/plain when multipart has more preferred child part.

**Comment by jech** [comment]
A possibly less fragile solution would be to add buttons for all the attachments just below the header area.

**Comment by ikazuhiro** [comment]
I've committed workaround at https://github.com/wanderlust/semi/commit/44aa82ecf78273d8ff4c84f2121b885fb7149f41 and I'm closing this issue.  If you still have a problem, please open new issue.
