### ISSUE TITLE
Incorrect decoding of format=flowed

### ISSUE THREAD

**Issue by jech** [wanderlust/semi#4]
A paragraph that consists of a single overlong line is not wrapped properly by `mime-display-text/plain-flowed`:

```
(with-temp-buffer
  (insert "Word")
  (dotimes (i 100) (insert " word"))
  (insert "\n")
  (mime-display-text/plain-flowed)
  (buffer-string))
```

Kazuhiro-san, please let me know if you intend to fix this issue, or whether you prefer me to rewrite the code from scratch (I find I'm unable to understand the current code, so I cannot fix it myself).

Thanks,

--jch

**Comment by ikazuhiro** [comment]
This is not a bug.  According to RFC 3676's ABNF, inserted text is "fixed-line".  Only "paragraph" would be filled.

**Comment by jech** [comment]
You're right.  (This implies that Mail.app is even more broken than I thought.  Grr.)

Sorry for the confusion,

--jch
