### ISSUE TITLE
incorrect keys in encryption

### ISSUE THREAD

**Issue by tats** [wanderlust/semi#9]
With SEMI-EPG 2015-05-03 and Wanderlust 2015-03-08, in encryption,
a mail with `To: ma@debian.org` chooses `dima@debian.org`'s key when
the foolowing keys are imported.
- `1024D/97AA33D6 Dima Barsky <dima@debian.org>`
- `1024D/1A944AD7 Martin Albert <ma@debian.org>`

It seems not exact match on an email address.

**Comment by tats** [comment]
Patch available at https://github.com/wanderlust/semi/pull/10

**Comment by ikazuhiro** [comment]
Thank you for the report.
I've committed the fix slightly different from yours.  Please test.

**Comment by tats** [comment]
Looks fine, and it works.  Thank you.
